GET 

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "Car",
    "password": "123456"
}

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "Car",
    "password": "123456",
    "emission": 3000
}


###
PATCH http://localhost:3000/auth/adjust/goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMSwiaWF0IjoxNjE4MDEyNDEwLCJleHAiOjE2MTgwMTMxMTB9.drHJ3Ix0WOJe9JIUQOCunXE9iyDrq0KwQfFn6kjbaJo


{
    "carbon_emission_goal": 1000
}

###
PATCH http://localhost:3000/auth/adjust/total
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMSwiaWF0IjoxNjE4MDEyNDEwLCJleHAiOjE2MTgwMTMxMTB9.drHJ3Ix0WOJe9JIUQOCunXE9iyDrq0KwQfFn6kjbaJo


{
    "result_grand_total": 6000
}

###
POST  http://localhost:3000/food/logfood
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMCwiaWF0IjoxNjE4ODU3NDM2LCJleHAiOjE2MTg5NDM4MzZ9.bo5CWK7ChDdl-DOGbtZgmdOiZE5PIozLrSb4N-FWtPw


{
    "result_food_total": 300,
    "food_serving": "[{meat:2}]"
}

###
GET  http://localhost:3000/food/entries
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozMCwiaWF0IjoxNjE4ODU3NDM2LCJleHAiOjE2MTg5NDM4MzZ9.bo5CWK7ChDdl-DOGbtZgmdOiZE5PIozLrSb4N-FWtPw
